{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"collapsed_sections":["GaLmDiaH7YRz","KET5yrRXIr-m"],"authorship_tag":"ABX9TyNnRMRXXeujRPoFVah5Pl4+"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","execution_count":1,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"bg36YEKvrrMp","executionInfo":{"status":"ok","timestamp":1684132768779,"user_tz":-480,"elapsed":30363,"user":{"displayName":"許哲維","userId":"02843931645315355142"}},"outputId":"87d22634-813f-42c6-9d3a-655155643c7a"},"outputs":[{"output_type":"stream","name":"stdout","text":["Mounted at /content/drive\n","/content/drive/MyDrive/Master/2020_fall/Machine_learning/修課 - 吳沛遠/Final Project\n"]}],"source":["from google.colab import drive\n","import os\n","import zipfile\n","drive.mount('/content/drive')\n","%cd \"/content/drive/MyDrive/Master/2020_fall/Machine_learning/修課 - 吳沛遠/Final Project/\""]},{"cell_type":"code","source":["import pandas as pd\n","import matplotlib.pyplot as plt\n","import seaborn as sns\n","import numpy as np\n","from scipy.stats import norm\n","from sklearn.preprocessing import StandardScaler\n","from scipy import stats\n","import warnings\n","warnings.filterwarnings('ignore')\n","%matplotlib inline"],"metadata":{"id":"-QEGusxSr3gD","executionInfo":{"status":"ok","timestamp":1684132815607,"user_tz":-480,"elapsed":2321,"user":{"displayName":"許哲維","userId":"02843931645315355142"}}},"execution_count":2,"outputs":[]},{"cell_type":"markdown","source":["# Data Pre-processing:"],"metadata":{"id":"GaLmDiaH7YRz"}},{"cell_type":"code","source":["import statsmodels.api as sm\n","from scipy.stats import t\n","from sklearn.impute import KNNImputer\n","\n","def preprocess(data, train_idx):\n","    train = data[:train_idx]\n","    ## skewness of dependent variable\n","    train['SalePrice'] = np.log1p(train['SalePrice'])\n","    train_wo_nan = train[train.columns[~train.isnull().any()]]\n","    \n","    ## remove outlier by studentized residual\n","    conti_var = train_wo_nan[train_wo_nan.columns[train_wo_nan.dtypes!=np.object]].columns.tolist()[1:-1]\n","    x = train_wo_nan[conti_var]\n","    x = sm.add_constant(x)\n","    y = train_wo_nan['SalePrice']\n","    model = sm.OLS(y, x).fit() \n","    # calculate studentized residuals \n","    stud_res = model.outlier_test() \n","\n","    # define predictor variable values and studentized residuals \n","    x = x.index.tolist()\n","    y = stud_res['student_resid']\n","    train_wo_out = train[(y<stats.t(df=len(y)-len(conti_var)-1).ppf((0.995))) & (y>stats.t(df=len(y)-len(conti_var)-1).ppf((0.005)))]\n","    \n","    # 完成training data remove outlier, 合併test data\n","    data_wo_out = pd.concat((train_wo_out, data[train_idx:]), sort=False).reset_index(drop=True)\n","    \n","    \n","    ## 補值\n","    data_wo_out[\"Alley\"][data_wo_out[\"Alley\"].isnull()]=0\n","    data_wo_out[\"Alley\"][data_wo_out[\"Alley\"]=='Grvl']=1\n","    data_wo_out[\"Alley\"][data_wo_out[\"Alley\"]=='Pave']=2\n","    data_wo_out[\"Alley\"]=pd.to_numeric(data_wo_out[\"Alley\"])\n","\n","    data_wo_out['MasVnrType'][data_wo_out['MasVnrType'].isnull()] = 'CBlock'\n","\n","    Bsmt_idx = data_wo_out[['BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2']].isnull().all(axis=1)\n","    qual = {'Ex':5, 'Gd':4, 'TA':3, 'Fa':2, 'Po':1}\n","    for col in ['BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2']:\n","      data_wo_out[col][Bsmt_idx] = 0\n","      for q in qual:\n","        data_wo_out[col][data_wo_out[col]==q] = qual[q]\n","\n","    Exp_Qual = {'Gd':4, 'Av':3, 'Mn':2, 'No':0}\n","    for q in Exp_Qual:\n","      data_wo_out['BsmtExposure'][data_wo_out['BsmtExposure']==q] = Exp_Qual[q]\n","\n","    Fin_Qual = {\"GLQ\":5,\"ALQ\":4,\"BLQ\":3,\"Rec\":2,\"LwQ\":1,\"Unf\":0}\n","    for q in Fin_Qual:\n","      data_wo_out['BsmtFinType1'][data_wo_out['BsmtFinType1']==q] = Fin_Qual[q]\n","      data_wo_out['BsmtFinType2'][data_wo_out['BsmtFinType2']==q] = Fin_Qual[q]\n","\n","    for i in ['BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2']:\n","      data_wo_out[i] = pd.to_numeric(data_wo_out[i])\n","\n","\n","    data_wo_out['FireplaceQu'][data_wo_out['Fireplaces']==0]=0\n","    for q in qual:\n","      data_wo_out['FireplaceQu'][data_wo_out['FireplaceQu']==q] = qual[q] \n","    data_wo_out['FireplaceQu'] = pd.to_numeric(data_wo_out['FireplaceQu'])\n","\n","    Garage_idx = data_wo_out[['GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageQual', 'GarageCond']].isnull().all(axis=1)\n","    for col in ['GarageType', 'GarageFinish', 'GarageQual', 'GarageCond']:\n","      data_wo_out[col][Garage_idx] = 'None'\n","    data_wo_out['GarageYrBlt'] = data_wo_out['GarageYrBlt'].max()+1-data_wo_out['GarageYrBlt']\n","    data_wo_out['GarageYrBlt'][Garage_idx]=0\n","    data_wo_out['GarageYrBlt'] = pd.to_numeric(data_wo_out['GarageYrBlt'])\n","\n","\n","    data_wo_out['PoolQC'][data_wo_out['PoolArea']==0]=0\n","    for q in qual:\n","      data_wo_out['PoolQC'][data_wo_out['PoolQC']==q] = qual[q]  \n","    data_wo_out['PoolQC'] = pd.to_numeric(data_wo_out['PoolQC'])\n","\n","    data_wo_out['Fence'][data_wo_out['Fence'].isnull()]=0\n","    FenceQual = {\"GdPrv\":4,\"MnPrv\":3,\"GdWo\":2,\"MnWw\":1}\n","    for q in FenceQual:\n","      data_wo_out['Fence'][data_wo_out['Fence']==q] = FenceQual[q]\n","    data_wo_out['Fence'] = pd.to_numeric(data_wo_out['Fence'])\n","\n","    data_wo_out[\"MiscFeature\"][data_wo_out[\"MiscFeature\"].isnull()] = \"None\"\n","\n","    ## several non consistent data filled up with mode or 0\n","    train_wo_out['BsmtExposure'][train_wo_out['BsmtExposure'].isnull()] = 0\n","    train_wo_out['BsmtFinType2'][train_wo_out['BsmtFinType2'].isnull()] = 0\n","    train_wo_out['Electrical'][train_wo_out['Electrical'].isnull()] = train_wo_out['Electrical'].mode().iloc[0]\n","    \n","    ## remove skewness\n","    cols = ['LotFrontage','LotArea', 'MasVnrArea','BsmtFinSF1','BsmtFinSF2','BsmtUnfSF','TotalBsmtSF',\n","            '1stFlrSF','2ndFlrSF','LowQualFinSF','GarageArea','WoodDeckSF',\n","            'OpenPorchSF','EnclosedPorch','3SsnPorch','ScreenPorch','GrLivArea','PoolArea','MiscVal']\n","    for col in cols:\n","      data_wo_out[col]=np.log1p(data_wo_out[col])\n","\n","    ## generate new variable\n","    data_wo_out = data_wo_out.assign(FullBath_n_2ndFlrSF = data_wo_out['FullBath'] * data_wo_out['2ndFlrSF'])\n","    data_wo_out = data_wo_out.assign(GarageCars_n_GarageArea = data_wo_out[\"GarageCars\"] * data_wo_out[\"GarageArea\"])\n","\n","    # 'TotalBsmtSF','1stFlrSF', '2ndFlrSF', 'GrLivArea' these paramters has visible linear relation with log(SalesPrice+1); we transfer them to x**2\n","    cols = ['TotalBsmtSF','1stFlrSF', '2ndFlrSF', 'GrLivArea']\n","    for col in cols:\n","      data_wo_out[col] = data_wo_out[col]**2\n","    \n","    # one- hot encoding for all np.object columns\n","    data_dum = pd.get_dummies(data_wo_out)\n","    data_wo_out = pd.DataFrame(data_dum)\n","\n","    # filled up Nans in numeric columns with KNN neighborhood \n","    data_wo_out_n_y = data_wo_out.drop([\"SalePrice\"], axis=1)\n","    imputer = KNNImputer(n_neighbors=5) \n","    imputed = imputer.fit_transform(data_wo_out_n_y) \n","    data_wo_out_KNN = pd.DataFrame(imputed, columns=data_wo_out_n_y.columns) \n","    y_train = data_wo_out[[\"SalePrice\"]][data_wo_out[\"Id\"]<=1460]\n","    x_train = data_wo_out_KNN[data_wo_out_KNN[\"Id\"]<=1460]\n","    x_test = data_wo_out_KNN[data_wo_out_KNN[\"Id\"]>1460]\n","    return x_train, y_train, x_test"],"metadata":{"id":"-qdPaRSS7K2x","executionInfo":{"status":"ok","timestamp":1684132816220,"user_tz":-480,"elapsed":616,"user":{"displayName":"許哲維","userId":"02843931645315355142"}}},"execution_count":3,"outputs":[]},{"cell_type":"code","source":["# prep data\n","train = pd.read_csv('train.csv')\n","test = pd.read_csv('test.csv')\n","\n","# concate train/test data\n","data = pd.concat((train, test), sort=False).reset_index(drop=True)\n","x_train, y_train, x_test = preprocess(data,1460)"],"metadata":{"id":"CUYmAihPDRQO","executionInfo":{"status":"ok","timestamp":1684132826015,"user_tz":-480,"elapsed":9798,"user":{"displayName":"許哲維","userId":"02843931645315355142"}}},"execution_count":4,"outputs":[]},{"cell_type":"code","source":["from sklearn.model_selection import train_test_split\n","x_train, x_valid, y_train, y_valid = train_test_split(x_train, y_train, test_size=0.3)"],"metadata":{"id":"aYoLUNXKafys","executionInfo":{"status":"ok","timestamp":1684132826015,"user_tz":-480,"elapsed":16,"user":{"displayName":"許哲維","userId":"02843931645315355142"}}},"execution_count":5,"outputs":[]},{"cell_type":"markdown","source":["# Modeling:"],"metadata":{"id":"ReFA3CwlQZJz"}},{"cell_type":"markdown","source":["Method Reference: https://medium.com/@permoonzz/kaggle-house-prices-advanced-regression-techniques-python-ensemble-learning%E5%AF%A6%E5%81%9A-99f757f4d326"],"metadata":{"id":"mhXEPO9gCu6-"}},{"cell_type":"markdown","source":["## Rule based method"],"metadata":{"id":"KET5yrRXIr-m"}},{"cell_type":"code","source":["## Regression: multiple regression, Ridge regression、Lasso、Elastic net、Support vector regression\n","\n","from sklearn.metrics import mean_squared_error\n","from sklearn.model_selection import cross_val_score, GridSearchCV, KFold, RandomizedSearchCV, train_test_split\n","import math\n","import sklearn.model_selection as ms\n","import sklearn.metrics as sklm"],"metadata":{"id":"sC45i4c7jLFk","executionInfo":{"status":"ok","timestamp":1684132826015,"user_tz":-480,"elapsed":14,"user":{"displayName":"許哲維","userId":"02843931645315355142"}}},"execution_count":6,"outputs":[]},{"cell_type":"code","source":["from sklearn.linear_model import LinearRegression\n","Linear = LinearRegression(fit_intercept=True)\n","\n","Linear_fit=Linear.fit(x_train,y_train)\n","\n","y_linear_train=Linear_fit.predict(x_train)\n","y_linear_valid=Linear_fit.predict(x_valid)\n","\n","# validation( train data and validate data)\n","print('RMSE_train_Linear = ' + str(math.sqrt(sklm.mean_squared_error(y_train, y_linear_train))))\n","print('RMSE_valid_Linear = ' + str(math.sqrt(sklm.mean_squared_error(y_valid, y_linear_valid))))"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"iF502mEajHAQ","executionInfo":{"status":"ok","timestamp":1684132826016,"user_tz":-480,"elapsed":15,"user":{"displayName":"許哲維","userId":"02843931645315355142"}},"outputId":"f037b033-b21d-434e-ce5e-c96764c5063a"},"execution_count":7,"outputs":[{"output_type":"stream","name":"stdout","text":["RMSE_train_Linear = 0.07428319495400032\n","RMSE_valid_Linear = 0.10600862867479989\n"]}]},{"cell_type":"code","source":["from sklearn.linear_model import RidgeCV\n","\n","alpha = [0.0001,0.001,0.01,0.1,1,10,100]\n","# find the best alpha and build model\n","Ridge = RidgeCV(cv=5, alphas=alpha) # the regressors X will be normalized before regression by subtracting the mean and dividing by the l2-norm.\n","\n","Ridge_fit=Ridge.fit(x_train,y_train)\n","\n","y_ridge_train=Ridge_fit.predict(x_train)\n","y_ridge_valid=Ridge_fit.predict(x_valid)\n","\n","# validation( train data and validate data)\n","print('RMSE_train_Ridge = ' + str(math.sqrt(sklm.mean_squared_error(y_train, y_ridge_train))))\n","print('RMSE_valid_Ridge = ' + str(math.sqrt(sklm.mean_squared_error(y_valid, y_ridge_valid))))"],"metadata":{"id":"PjK1gq3LGxIV","executionInfo":{"status":"ok","timestamp":1684132827602,"user_tz":-480,"elapsed":1590,"user":{"displayName":"許哲維","userId":"02843931645315355142"}},"colab":{"base_uri":"https://localhost:8080/"},"outputId":"79aa5a85-78dd-41aa-9d77-cb0931eb9d19"},"execution_count":8,"outputs":[{"output_type":"stream","name":"stdout","text":["RMSE_train_Ridge = 0.08006972558233426\n","RMSE_valid_Ridge = 0.09736388331325928\n"]}]},{"cell_type":"code","source":["# LASSO:\n","from sklearn.linear_model import LassoCV\n","# set cross-validation alpha\n","alpha = [0.0001,0.001,0.01,0.1,1,10,100]\n","# find the best alpha and build model\n","Lasso = LassoCV(cv=5, alphas=alpha)\n","Lasso_fit=Lasso.fit(x_train,y_train)\n","y_lasso_train=Lasso_fit.predict(x_train)\n","y_lasso_valid=Lasso_fit.predict(x_valid)\n","# validation( train data and validate data)\n","print('RMSE_train_Lasso = ' + str(math.sqrt(sklm.mean_squared_error(y_train, y_lasso_train))))\n","print('RMSE_valid_Lasso = ' + str(math.sqrt(sklm.mean_squared_error(y_valid, y_lasso_valid))))"],"metadata":{"id":"AciT8Swn4HTm","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1684132827602,"user_tz":-480,"elapsed":4,"user":{"displayName":"許哲維","userId":"02843931645315355142"}},"outputId":"6174b8ee-b94b-4931-d1c6-5ee090625d57"},"execution_count":9,"outputs":[{"output_type":"stream","name":"stdout","text":["RMSE_train_Lasso = 0.08789150355407639\n","RMSE_valid_Lasso = 0.09730802550094862\n"]}]},{"cell_type":"code","source":["from sklearn.linear_model import ElasticNetCV\n","# set cross-validation alpha and l1ratio\n","alpha=[0.0001,0.001,0.01,0.1,1,10,100]\n","l1ratio = [0.1, 0.5, 0.9, 0.95, 0.99, 1]\n","# find the best alpha/l1ratio and build model\n","elastic_cv = ElasticNetCV(cv=5,max_iter=int(1e7),alphas=alpha, l1_ratio=l1ratio)\n","elastic_fit = elastic_cv.fit(x_train, y_train)\n","y_el_train=elastic_fit.predict(x_train)\n","y_el_valid=elastic_fit.predict(x_valid)\n","# validation( train data and validate data)\n","print('RMSE_train_ElasticNet = ' + str(math.sqrt(sklm.mean_squared_error(y_train, y_el_train))))\n","print('RMSE_valid_ElasticNet = ' + str(math.sqrt(sklm.mean_squared_error(y_valid, y_el_valid))))"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"47tp3tBESULs","executionInfo":{"status":"ok","timestamp":1684132834196,"user_tz":-480,"elapsed":6597,"user":{"displayName":"許哲維","userId":"02843931645315355142"}},"outputId":"773c2343-ecf3-4cde-cf8d-46622d9d674e"},"execution_count":10,"outputs":[{"output_type":"stream","name":"stdout","text":["RMSE_train_ElasticNet = 0.0843504581764004\n","RMSE_valid_ElasticNet = 0.09762467208208711\n"]}]},{"cell_type":"code","source":["from sklearn.svm import SVR\n","CV = {}\n","alpha=[1,10,100,1000,1e4,1e5]\n","for alp in alpha:\n","  svr = SVR(kernel='rbf', C=alp)\n","  svr_fit=svr.fit(x_train, y_train)\n","  y_svr_train=svr_fit.predict(x_train)\n","  y_svr_valid=svr_fit.predict(x_valid)\n","  # validation( train data and validate data)\n","  CV[alp] = math.sqrt(sklm.mean_squared_error(y_valid, y_svr_valid))\n","\n","C = [key for key, cv in CV.items() if cv==min(CV.values())]\n","svr = SVR(kernel='rbf', C=C[0])\n","svr_fit=svr.fit(x_train, y_train)\n","y_svr_train=svr_fit.predict(x_train)\n","y_svr_valid=svr_fit.predict(x_valid)\n","print('C = ' + str(C[0]) + ', RMSE_train_svr = ' + str(math.sqrt(sklm.mean_squared_error(y_train, y_svr_train))))\n","print('C = ' + str(C[0]) + ', RMSE_valid_svr = ' + str(math.sqrt(sklm.mean_squared_error(y_valid, y_svr_valid))))"],"metadata":{"id":"SjT-sHqYybPq","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1684132853248,"user_tz":-480,"elapsed":19061,"user":{"displayName":"許哲維","userId":"02843931645315355142"}},"outputId":"676d21aa-f257-495f-d3eb-3861d5eb1dce"},"execution_count":11,"outputs":[{"output_type":"stream","name":"stdout","text":["C = 100000.0, RMSE_train_svr = 0.07840236699955484\n","C = 100000.0, RMSE_valid_svr = 0.09959188072551768\n"]}]},{"cell_type":"markdown","source":["## Boosting method: Adaboost、Gradient boosting、XGBoost、Staking、LightGBM"],"metadata":{"id":"gc9UMF8ZsWTL"}},{"cell_type":"code","source":["from lightgbm import LGBMRegressor\n","estimator=LGBMRegressor()\n","parameter_grid={'max_depth':range(2,5,1),\n","        'learning_rate':np.linspace(0.001,1,20),\n","        'feature_fraction':np.linspace(0.5,0.99,20),\n","        'bagging_fraction':np.linspace(0.1,0.99,20),\n","        'bagging_freq':range(5,10,1),\n","        'num_leaves':range(100,200,5),\n","        'min_data_in_leaf':range(50,200,10),\n","        'n_estimators':range(100,5000,100)}\n","grid = RandomizedSearchCV(estimator,parameter_grid,cv=3,scoring='neg_root_mean_squared_error',n_iter=int(5e2),n_jobs=-1)\n","grid.fit(x_train, y_train)\n","# print best parameter combination\n","print(grid.best_params_)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"3xi8n9COk4hK","executionInfo":{"status":"ok","timestamp":1684133878089,"user_tz":-480,"elapsed":1024854,"user":{"displayName":"許哲維","userId":"02843931645315355142"}},"outputId":"05313078-1788-4915-d0c6-903e515eafe6"},"execution_count":12,"outputs":[{"output_type":"stream","name":"stdout","text":["[LightGBM] [Warning] Unknown parameter: bagging_frequency\n","[LightGBM] [Warning] feature_fraction is set=0.7321052631578947, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7321052631578947\n","[LightGBM] [Warning] min_data_in_leaf is set=50, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=50\n","[LightGBM] [Warning] bagging_fraction is set=0.7089473684210525, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7089473684210525\n","{'num_leaves': 100, 'n_estimators': 700, 'min_data_in_leaf': 50, 'max_depth': 2, 'learning_rate': 0.1061578947368421, 'feature_fraction': 0.7321052631578947, 'bagging_frequency': 7, 'bagging_fraction': 0.7089473684210525}\n"]}]},{"cell_type":"code","source":["lightgbm = LGBMRegressor(objective='regression', \n","                         num_leaves=grid.best_params_[\"num_leaves\"],\n","                         min_data_in_leaf=20,\n","                         learning_rate=grid.best_params_[\"learning_rate\"],\n","                         n_estimators=grid.best_params_[\"n_estimators\"],\n","                         metric=\"rmse\",\n","                         max_depth=grid.best_params_[\"max_depth\"],\n","                         bagging_fraction=grid.best_params_[\"bagging_fraction\"],\n","                         bagging_freq=grid.best_params_[\"bagging_frequency\"],\n","                         bagging_seed=9,\n","                         feature_fraction=grid.best_params_[\"feature_fraction\"],\n","                         feature_fraction_seed=7,\n","                         verbose=-1)\n","lgbm_fit = lightgbm.fit(x_train, y_train)\n","y_lgbm_train=lgbm_fit.predict(x_train)\n","y_lgbm_valid=lgbm_fit.predict(x_valid)\n","print('RMSE_train_LGBM = ' + str(math.sqrt(sklm.mean_squared_error(y_train, y_lgbm_train))))\n","print('RMSE_valid_LGBM = ' + str(math.sqrt(sklm.mean_squared_error(y_valid, y_lgbm_valid))))"],"metadata":{"id":"CDAsSjxTmh6w","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1684133878090,"user_tz":-480,"elapsed":5,"user":{"displayName":"許哲維","userId":"02843931645315355142"}},"outputId":"6c44f987-2904-46d8-ef92-a0b974bc5309"},"execution_count":13,"outputs":[{"output_type":"stream","name":"stdout","text":["RMSE_train_LGBM = 0.05054890078784122\n","RMSE_valid_LGBM = 0.09996264805327666\n"]}]},{"cell_type":"code","source":["from xgboost.sklearn import XGBRegressor\n","estimator=XGBRegressor()\n","parameter_grid={\n","        'max_depth':range(2,8,1),\n","        'learning_rate':np.linspace(0.001,1,20),\n","        'colsample_bytree':np.linspace(0.1,0.99,20),\n","        'n_estimators':range(100,5000,100),\n","        'min_child_weight':np.linspace(1,5,20),\n","        'gamma':np.linspace(0.1,0.99,20),\n","        'subsample':np.linspace(0.1,0.9,20),\n","        'reg_alpha':np.linspace(0.01,3,20),\n","        'reg_lambda':np.linspace(0.01,3,20)}\n","grid = RandomizedSearchCV(estimator,parameter_grid,cv=3,scoring = 'neg_root_mean_squared_error',n_iter=int(5e2),n_jobs=-1)\n","grid.fit(x_train, y_train)\n","# print best parameter combination\n","print (grid.best_params_)"],"metadata":{"id":"krxXGziuw21g","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1684151272748,"user_tz":-480,"elapsed":17394661,"user":{"displayName":"許哲維","userId":"02843931645315355142"}},"outputId":"40e2929d-da3b-4deb-942e-a88253e32b74"},"execution_count":14,"outputs":[{"output_type":"stream","name":"stdout","text":["{'subsample': 0.3526315789473684, 'reg_lambda': 0.9542105263157896, 'reg_alpha': 0.1673684210526316, 'n_estimators': 1700, 'min_child_weight': 3.7368421052631575, 'max_depth': 5, 'learning_rate': 0.2113157894736842, 'gamma': 0.1, 'colsample_bytree': 0.5684210526315789}\n"]}]},{"cell_type":"code","source":["xgb= XGBRegressor(base_score=0.5, \n","          booster='gbtree', \n","          colsample_bylevel=1,\n","          colsample_bynode=1, \n","          colsample_bytree=grid.best_params_[\"colsample_bytree\"], \n","          gamma=grid.best_params_[\"gamma\"],\n","          importance_type='gain', \n","          learning_rate=grid.best_params_[\"learning_rate\"],\n","          max_delta_step=0,\n","          max_depth=grid.best_params_[\"max_depth\"], \n","          missing=1, \n","          min_child_weight=grid.best_params_[\"min_child_weight\"],\n","          n_estimators=grid.best_params_[\"n_estimators\"],\n","          n_jobs=1, \n","          nthread=None, \n","          objective='reg:squarederror', \n","          random_state=0,\n","          reg_lambda=grid.best_params_[\"reg_lambda\"],\n","          reg_alpha=grid.best_params_[\"reg_alpha\"],\n","          scale_pos_weight=1, \n","          seed=None,\n","          silent=None, \n","          subsample=grid.best_params_[\"subsample\"], \n","          verbosity=1)\n","xgb_fit = xgb.fit(x_train, y_train)\n","y_xgb_train=xgb_fit.predict(x_train)\n","y_xgb_valid=xgb_fit.predict(x_valid)\n","print('RMSE_train_XGB = ' + str(math.sqrt(sklm.mean_squared_error(y_train, y_xgb_train))))\n","print('RMSE_valid_XGB = ' + str(math.sqrt(sklm.mean_squared_error(y_valid, y_xgb_valid))))"],"metadata":{"id":"h8-lGz5Lw8ki","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1684151287489,"user_tz":-480,"elapsed":14746,"user":{"displayName":"許哲維","userId":"02843931645315355142"}},"outputId":"974134c1-c0f9-4ce3-d493-2bfa9c01e0f3"},"execution_count":15,"outputs":[{"output_type":"stream","name":"stdout","text":["RMSE_train_XGB = 0.08070159787335034\n","RMSE_valid_XGB = 0.11283729769354162\n"]}]},{"cell_type":"markdown","source":["# Voting, Stacking, Blending"],"metadata":{"id":"T0hSRa8Wa-nk"}},{"cell_type":"code","source":["from sklearn.ensemble import VotingRegressor\n","# Build Model\n","vote_mod = VotingRegressor([('Ridge', Ridge_fit), ('Lasso',Lasso_fit),('Elastic',elastic_fit),('lgbm',lgbm_fit),('xgb',xgb_fit)])\n","vote = vote_mod.fit(x_train, y_train.values.ravel())\n","# predict train/test y\n","vote_pred_train=vote.predict(x_train)\n","vote_pred_valid=vote.predict(x_valid)\n","# validation( train data and validate data)\n","print('RMSE_train_Voting = ' + str(math.sqrt(sklm.mean_squared_error(y_train, vote_pred_train))))\n","print('RMSE_valid_Voting = ' + str(math.sqrt(sklm.mean_squared_error(y_valid, vote_pred_valid))))"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"eSLxDu9ZbEGG","executionInfo":{"status":"ok","timestamp":1684151308097,"user_tz":-480,"elapsed":20621,"user":{"displayName":"許哲維","userId":"02843931645315355142"}},"outputId":"965c5635-065a-4be8-df11-b5338d144567"},"execution_count":16,"outputs":[{"output_type":"stream","name":"stdout","text":["[LightGBM] [Warning] feature_fraction is set=0.7321052631578947, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7321052631578947\n","[LightGBM] [Warning] min_data_in_leaf is set=20, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=20\n","[LightGBM] [Warning] bagging_freq is set=7, subsample_freq=0 will be ignored. Current value: bagging_freq=7\n","[LightGBM] [Warning] bagging_fraction is set=0.7089473684210525, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7089473684210525\n","RMSE_train_Voting = 0.0711907344351661\n","RMSE_valid_Voting = 0.09379223744549266\n"]}]},{"cell_type":"code","source":["from mlxtend.regressor import StackingRegressor\n","from sklearn.ensemble import GradientBoostingRegressor\n","# Build Model\n","gbdt=GradientBoostingRegressor(learning_rate=0.05,\n","                max_leaf_nodes=3,\n","                n_estimators=100)\n","stregr = StackingRegressor(regressors=[Ridge_fit, Lasso_fit, elastic_fit, lgbm_fit,xgb_fit], \n","                           meta_regressor=gbdt, \n","                           use_features_in_secondary=True)\n","stack_mod=stregr.fit(x_train, y_train.values.ravel())\n","# predict train/test y\n","stacking_pred_train=stack_mod.predict(x_train)\n","stacking_pred_valid=stack_mod.predict(x_valid)\n","# validation( train data and validate data)\n","print('RMSE_train_Stacking = ' + str(math.sqrt(sklm.mean_squared_error(y_train, stacking_pred_train))))\n","print('RMSE_valid_Stacking = ' + str(math.sqrt(sklm.mean_squared_error(y_valid, stacking_pred_valid))))"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"u00KFHHWbFT1","outputId":"c3727f51-2140-4dd4-8034-fd9220ee587d"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stderr","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"output_type":"stream","name":"stdout","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-17-d74fba26e0ae>\", line 1, in <cell line: 1>\n","    from mlxtend.regressor import StackingRegressor\n","  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n","  File \"<frozen importlib._bootstrap>\", line 1002, in _find_and_load_unlocked\n","  File \"<frozen importlib._bootstrap>\", line 945, in _find_spec\n","  File \"<frozen importlib._bootstrap_external>\", line 1439, in find_spec\n","  File \"<frozen importlib._bootstrap_external>\", line 1408, in _get_spec\n","  File \"<frozen importlib._bootstrap_external>\", line 1366, in _path_importer_cache\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-17-d74fba26e0ae>\", line 1, in <cell line: 1>\n","    from mlxtend.regressor import StackingRegressor\n","  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n","  File \"<frozen importlib._bootstrap>\", line 1002, in _find_and_load_unlocked\n","  File \"<frozen importlib._bootstrap>\", line 945, in _find_spec\n","  File \"<frozen importlib._bootstrap_external>\", line 1439, in find_spec\n","  File \"<frozen importlib._bootstrap_external>\", line 1408, in _get_spec\n","  File \"<frozen importlib._bootstrap_external>\", line 1366, in _path_importer_cache\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-17-d74fba26e0ae>\", line 1, in <cell line: 1>\n","    from mlxtend.regressor import StackingRegressor\n","  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n","  File \"<frozen importlib._bootstrap>\", line 1002, in _find_and_load_unlocked\n","  File \"<frozen importlib._bootstrap>\", line 945, in _find_spec\n","  File \"<frozen importlib._bootstrap_external>\", line 1439, in find_spec\n","  File \"<frozen importlib._bootstrap_external>\", line 1408, in _get_spec\n","  File \"<frozen importlib._bootstrap_external>\", line 1366, in _path_importer_cache\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}]},{"cell_type":"code","source":["# set weight list\n","weight=list(np.linspace(0.1,1,91))\n","# create outcome dataframe \n","train_mse=[]\n","valid_mse=[]\n","for i in weight:\n","    blending_pred_train=(i*vote_pred_train)+((1-i)*stacking_pred_train)\n","    blending_pred_valid=(i*vote_pred_valid)+((1-i)*stacking_pred_valid)\n","    train_mse.append(math.sqrt(sklm.mean_squared_error(y_train, blending_pred_train)))\n","    valid_mse.append(math.sqrt(sklm.mean_squared_error(y_valid, blending_pred_valid)))\n","blending_output=pd.DataFrame({'weight':weight,\n","                       'train_mse':train_mse,\n","                       'valid_mse':valid_mse})\n","# print top 10 weight value\n","weight = blending_output.sort_values(by=['valid_mse'],ascending=True)\n","print(weight.head(10))"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"metiS3R3bIxl","outputId":"8ed645f3-2190-4db3-e084-e8f7341cc242"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stderr","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"output_type":"stream","name":"stdout","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-17-d9dddf9dc5af>\", line 7, in <cell line: 6>\n","    blending_pred_train=(i*vote_pred_train)+((1-i)*stacking_pred_train)\n","NameError: name 'stacking_pred_train' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'NameError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-17-d9dddf9dc5af>\", line 7, in <cell line: 6>\n","    blending_pred_train=(i*vote_pred_train)+((1-i)*stacking_pred_train)\n","NameError: name 'stacking_pred_train' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'NameError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n"]},{"output_type":"stream","name":"stderr","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"output_type":"stream","name":"stdout","text":["  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-17-d9dddf9dc5af>\", line 7, in <cell line: 6>\n","    blending_pred_train=(i*vote_pred_train)+((1-i)*stacking_pred_train)\n","NameError: name 'stacking_pred_train' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'NameError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}]},{"cell_type":"markdown","source":["# Submit the predict data"],"metadata":{"id":"jZGIEKpAomuc"}},{"cell_type":"code","source":["# predict and blending\n","final_pred_voting=vote.predict(x_test)\n","final_pred_stacking=stack_mod.predict(x_test)\n","w = weight.iloc[0][\"weight\"]\n","final_pred_blending=w*final_pred_voting+(1-w)*final_pred_stacking\n","# reverse log y\n","final_pred_blending=np.expm1(final_pred_blending)\n","a=list(range(1461,2920,1))\n","submit=pd.DataFrame({'Id':list(range(1461,2920,1)),\n","                     'SalePrice':final_pred_blending})\n","    \n","# save as csv     \n","submit.to_csv('submit.csv',index=False)"],"metadata":{"id":"5TqbbWO_olhA","colab":{"base_uri":"https://localhost:8080/"},"outputId":"642adea4-c65b-4fd8-d794-bc2dc13825b2"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stderr","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"output_type":"stream","name":"stdout","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-17-0dcd49c6e20c>\", line 3, in <cell line: 3>\n","    final_pred_stacking=stack_mod.predict(x_test)\n","NameError: name 'stack_mod' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'NameError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-17-0dcd49c6e20c>\", line 3, in <cell line: 3>\n","    final_pred_stacking=stack_mod.predict(x_test)\n","NameError: name 'stack_mod' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'NameError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-17-0dcd49c6e20c>\", line 3, in <cell line: 3>\n","    final_pred_stacking=stack_mod.predict(x_test)\n","NameError: name 'stack_mod' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'NameError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}]}]}